spring:
	profiles:
       active:
       	 - dev
------
spring:
	profiles: dev
    application:
         name: shop-config-dev

spring:
    profiles: test
    application:
         name: shop-config-test